#!/bin/bash

#tim sayre tim@kitswv.com Kanwha IT Security, ltd.  
#taken from Miguel Grinberg http://blog.miguelgrinberg.com/post/how-to-build-and-run-mjpg-streamer-on-the-raspberry-pi

#Start the camera
mkdir /tmp/stream
raspistill --nopreview -w 640 -h 480 -q 5 -o /tmp/stream/pic.jpg -tl 100 -t 9999999 -th 0:0:0 &

#Start the streamer
LD_LIBRARY_PATH=/usr/local/lib mjpg_streamer -i "input_file.so -f /tmp/stream -n pic.jpg" -o "output_http.so -w /usr/local/www"

#Watch the stream
#http://<IP-address>:8080
